version: '3.7'
services:

  lab0-project:
    build: ../.
    container_name: lab0-projects
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://postgresqldb:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - postgresqldb
    networks:
      - my-network

  postgresqldb:
    image: postgres
    container_name: postgresqldb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - my-network

volumes:
  postgres-data: {}

networks:
  my-network:
    driver: bridge