spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/user
    username: postgres
    password: s3cret
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
    database: postgresql

# Open API
springdoc:
  swagger-ui:
    path: /swagger-ui.html